/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vcon_final;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.ModelMeetings;
import model.ModelUser;

/**
 *
 * @author User
 */
public class JoinMeet extends javax.swing.JFrame {

    String Username;
    ModelUser User;

    /**
     * Creates new form JoinMeet
     */
    public JoinMeet() {
        initComponents();
    }

    public void InitUsername(String Username) {
        this.Username = Username;
        String Query = "SELECT * FROM `users` WHERE `username` = ?";

        PreparedStatement PreparedStat;
        ResultSet ResultSett;
        try {
            PreparedStat = DBconnection.getConnection().prepareStatement(Query);
            PreparedStat.setString(1, Username);
            ResultSett = PreparedStat.executeQuery();
            User = new ModelUser();
            if (ResultSett.next()) {

                User.setNim(ResultSett.getInt("nim"));
                User.setFull_name(ResultSett.getString("full_name"));
                User.setGender(ResultSett.getString("gender"));
                User.setPhone(ResultSett.getString("phone"));
                User.setUsername(ResultSett.getString("username"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("cek:" + User.getUsername() + " : " + User.getNim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edt_passcode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mohon untuk masukkan passcode anda!");

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_kembali.setText("Back");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(edt_passcode, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edt_passcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_kembali)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        TrackMeeting(this.edt_passcode.getText().toString());
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        this.hide();
        Menu from = new Menu();
        from.setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed
    public void TrackMeeting(String passCode) {
        String Query = "SELECT * FROM `meetings` WHERE `passcode` = ?";

        PreparedStatement PreparedStat;
        ResultSet ResultSett;
        ModelMeetings model = new ModelMeetings();

        try {
            PreparedStat = DBconnection.getConnection().prepareStatement(Query);
            PreparedStat.setString(1, passCode);
            ResultSett = PreparedStat.executeQuery();
            if (ResultSett.next()) {
                model.setId_meet(ResultSett.getInt("id_meeting"));
                model.setHost(ResultSett.getString("nama_host"));
                model.setJudul(ResultSett.getString("judul_meeting"));
                model.setSchedule(ResultSett.getDate("jadwal"));
                model.setNim(ResultSett.getInt("nim"));
                model.setPasscode(ResultSett.getString("passcode"));
                CreateMeeting meeting = new CreateMeeting();
                meeting.setVisible(true);
                meeting.pack();
                meeting.setLocationRelativeTo(null);
                meeting.JoinMeeting(User, model);
                this.dispose();
            } else {
                System.out.println("Pass Code tidak ada!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("cek:" + model.getJudul() + " : " + model.getHost());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinMeet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinMeet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinMeet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinMeet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoinMeet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_submit;
    private javax.swing.JTextField edt_passcode;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
