/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vcon_final;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModelUser;

/**
 *
 * @author sada technology
 */
public class Participant extends javax.swing.JFrame {

    List<ModelUser> listParticipant = new ArrayList<>();
    ModelUser user;
    String passCode;

    /**
     * Creates new form Participant
     */
    public Participant() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.btn_kick_participant.setVisible(false);
    }

    public void loadParticipant(String host, ModelUser user1, String passCode) {
        this.user = user1;
        this.passCode = passCode;
        if (host.equalsIgnoreCase(this.user.getFull_name())) {
            this.btn_kick_participant.setVisible(true);
        }

        String query = "SELECT * FROM `users` WHERE `pass_code` = ?";

        PreparedStatement st;
        ResultSet rs;
        try {
            st = DBconnection.getConnection().prepareStatement(query);
            st.setString(1, passCode);
            rs = st.executeQuery();
            ModelUser user;
            while (rs.next()) {
                user = new ModelUser();
                user.setNim(rs.getInt("nim"));
                user.setFull_name(rs.getString("full_name"));
                user.setGender(rs.getString("gender"));
                user.setPhone(rs.getString("phone"));
                user.setUsername(rs.getString("username"));
                listParticipant.add(user);
            }

        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel pilih = new DefaultListModel();
        for (int i = 0; i < listParticipant.size(); i++) {
            pilih.addElement(listParticipant.get(i).getFull_name());
        }
        this.jlist_participant.setModel(pilih);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_participant = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btn_kick_participant = new javax.swing.JButton();
        btn_invite_participant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlist_participant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlist_participantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlist_participant);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Participant");

        btn_kick_participant.setText("Kick Participant");
        btn_kick_participant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kick_participantActionPerformed(evt);
            }
        });

        btn_invite_participant.setText("Invite Participant");
        btn_invite_participant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invite_participantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_invite_participant, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kick_participant, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kick_participant, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_invite_participant, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlist_participantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlist_participantMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
//        this.txt_nama.setText(listPegawai.get(this.jlist_participant.getAnchorSelectionIndex()).getName());
//        this.txt_posisi.setText(listPegawai.get(this.jlist_participant.getAnchorSelectionIndex()).getPosisi());
//        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        String dateBirth = dateFormat.format(listPegawai.get(this.jlist_participant.getAnchorSelectionIndex()).getBirth_date());
//
//        this.txt_tgl_lahir.setText(dateBirth);
    }//GEN-LAST:event_jlist_participantMouseClicked

    private void btn_kick_participantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kick_participantActionPerformed
        int position = this.jlist_participant.getSelectedIndex();
        System.out.println(this.jlist_participant.getSelectedIndex() + " cek aja sih");
        if (position == -1) {
            JOptionPane.showMessageDialog(this, "Mohon untuk pilih participant terlebih dahulu!");
            return;
        }
        if (user.getNim() == listParticipant.get(position).getNim()) {
            JOptionPane.showMessageDialog(this, "Tidak bisa kick diri anda sendiri!!");
            return;
        }
        int jawab = JOptionPane.showOptionDialog(this,
                "Apakah anda yakin untuk melakukan kick participant?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (jawab == JOptionPane.YES_OPTION) {
            try {
                String updateQuery = "UPDATE users SET pass_code = '" + null + "' WHERE `nim` =" + listParticipant.get(position).getNim();
                PreparedStatement preparedStmt = DBconnection.getConnection().prepareStatement(updateQuery);

                preparedStmt.execute();
                JOptionPane.showMessageDialog(null, "Participant Berhasil Terkick!");
                listParticipant.remove(position);
            } catch (Exception e) {
                System.err.println("Got an exception! ");
                System.err.println(e.getMessage());
            }
            DefaultListModel pilih = new DefaultListModel();
            for (int i = 0; i < listParticipant.size(); i++) {
                pilih.addElement(listParticipant.get(i).getFull_name());
            }
            this.jlist_participant.setModel(pilih);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn_kick_participantActionPerformed

    private void btn_invite_participantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invite_participantActionPerformed
        this.dispose();
        Invite_Participant Invite_Participant = new Invite_Participant();
        Invite_Participant.setVisible(true);
        Invite_Participant.pack();
        Invite_Participant.setPassCode(passCode);
        Invite_Participant.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_invite_participantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Participant.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Participant.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Participant.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Participant.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Participant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_invite_participant;
    private javax.swing.JButton btn_kick_participant;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlist_participant;
    // End of variables declaration//GEN-END:variables
}
