/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vcon_final;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModelChat;
import model.ModelUser;

/**
 *
 * @author sada technology
 */
public class RoomChat extends javax.swing.JFrame {

    ModelUser user;
    String passCode;
    ModelChat modelChat;
    List<ModelChat> listChat = new ArrayList<>();

    /**
     * Creates new form RoomChat
     */
    public RoomChat() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void initRoomChat(ModelUser user, String passCode) {
        this.user = user;
        this.passCode = passCode;

        String query = "SELECT * FROM `chat` WHERE `passcode` = ?";
        listChat.clear();

        PreparedStatement st;
        ResultSet rs;
        try {
            st = DBconnection.getConnection().prepareStatement(query);
            st.setString(1, passCode);
            rs = st.executeQuery();

            while (rs.next()) {
                modelChat = new ModelChat();
                modelChat.setId_chat(rs.getInt("id_chat"));
                modelChat.setMessage(rs.getString("message"));
                modelChat.setDate(rs.getDate("date"));
                modelChat.setPassCode(rs.getString("passcode"));
                listChat.add(modelChat);
            }

        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel pilih = new DefaultListModel();
        for (int i = 0; i < listChat.size(); i++) {
            pilih.addElement(listChat.get(i).getMessage());
        }
        this.jlist_chat.setModel(pilih);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_chat = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        edt_chat = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlist_chat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlist_chatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlist_chat);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chat User");

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(edt_chat, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edt_chat)
                    .addComponent(btn_send, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlist_chatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlist_chatMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        //        this.txt_nama.setText(listPegawai.get(this.jlist_participant.getAnchorSelectionIndex()).getName());
        //        this.txt_posisi.setText(listPegawai.get(this.jlist_participant.getAnchorSelectionIndex()).getPosisi());
        //        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //        String dateBirth = dateFormat.format(listPegawai.get(this.jlist_participant.getAnchorSelectionIndex()).getBirth_date());
        //        this.txt_tgl_lahir.setText(dateBirth);
    }//GEN-LAST:event_jlist_chatMouseClicked

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        if (edt_chat.getText().toString().length() >= 60) {
            JOptionPane.showMessageDialog(this, "Chat tidak boleh lebih dari 60 kata!");
            return;
        }
        addChat(edt_chat.getText().toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sendActionPerformed
    private void addChat(String message) {
        PreparedStatement ps;
        ResultSet rs;

        String registerUserQuery = "INSERT INTO `chat`(`message`, `date`, `passcode`)VALUES(?,?,?)";

        try {
            Date date = new Date(System.currentTimeMillis());
            ps = DBconnection.getConnection().prepareStatement(registerUserQuery);
            ps.setString(1, user.getFull_name() + ": " + message);
            ps.setDate(2, date);
            ps.setString(3, passCode);

            if (ps.executeUpdate() != 0) {
                initRoomChat(user, passCode);
                this.edt_chat.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JTextField edt_chat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlist_chat;
    // End of variables declaration//GEN-END:variables
}
